Getting Help
------------
include::attributes.txt[]


Proxmox VE Wiki
~~~~~~~~~~~~~~~

The primary source of information is the {pve}
http://pve.proxmox.com[wiki]. It combines the reference documentaion
with user contributed content.


Community Support Forum
~~~~~~~~~~~~~~~~~~~~~~~

{pve} itself is fully open source, so we always encourage our users to
discuss and share their knowledge using the
http://forum.proxmox.com/[Community Support Forum]. The forum is fully
moderated by the Proxmox support team, and has a quite large user base
around the whole world. Needless to say that such a large forum is a
great place to get information.

Mailing Lists
~~~~~~~~~~~~~

This is a fast way to communicate via email with the Proxmox VE
community

* Mailing list for users:
  http://pve.proxmox.com/cgi-bin/mailman/listinfo/pve-user[PVE User
  List]

The primary communication channel for developers is:

* Mailing list for developer:
  http://pve.proxmox.com/cgi-bin/mailman/listinfo/pve-devel[PVE
  development discussion]


Commercial Support
~~~~~~~~~~~~~~~~~~

{proxmoxGmbh} also offers a commercial support channel. {pve} server
subscriptions can be ordered online, see
http://shop.maurer-it.com[{pve} Shop]. For all details see
http://www.proxmox.com/proxmox-ve/pricing[{pve} Subscription Service
Plans]. Please contact the mailto:office@proxmox.com[Proxmox sales
team] for commercial support requests or volume discounts.


Bug Tracker
~~~~~~~~~~~

We also run a public a public bug tracker at
https://bugzilla.proxmox.com. If you ever detect a bug, you can file
an bug entry there. This makes it easy to track the bug status, and
you will get notified as soon as the bug is fixed.
