Logical Volume Manager (LVM)
----------------------------
include::attributes.txt[]

ifdef::wiki[]
:pve-toplevel:
endif::wiki[]

Most people install {pve} directly on a local disk. The {pve}
installation CD offers several options for local disk management, and
the current default setup uses LVM. The installer let you select a
single disk for such setup, and uses that disk as physical volume for
the **V**olume **G**roup (VG) `pve`. The following output is from a
test installation using a small 8GB disk:

----
# pvs
  PV         VG   Fmt  Attr PSize PFree  
  /dev/sda3  pve  lvm2 a--  7.87g 876.00m

# vgs
  VG   #PV #LV #SN Attr   VSize VFree  
  pve    1   3   0 wz--n- 7.87g 876.00m
----

The installer allocates three **L**ogical **V**olumes (LV) inside this
VG:

----
# lvs
  LV   VG   Attr       LSize   Pool Origin Data%  Meta%
  data pve  twi-a-tz--   4.38g             0.00   0.63
  root pve  -wi-ao----   1.75g
  swap pve  -wi-ao---- 896.00m     
----

root:: Formatted as `ext4`, and contains the operation system.

swap:: Swap partition

data:: This volume uses LVM-thin, and is used to store VM
images. LVM-thin is preferable for this task, because it offers
efficient support for snapshots and clones.

Hardware
~~~~~~~~

We highly recommend to use a hardware RAID controller (with BBU) for
such setups. This increases performance, provides redundancy, and make
disk replacements easier (hot-pluggable).

LVM itself does not need any special hardware, and memory requirements
are very low.


Bootloader
~~~~~~~~~~

We install two boot loaders by default. The first partition contains
the standard GRUB boot loader. The second partition is an **E**FI **S**ystem
**P**artition (ESP), which makes it possible to boot on EFI systems.
