[[chapter_gui]]
Graphical User Interface
========================
ifndef::manvolnum[]
:pve-toplevel:
endif::manvolnum[]

{pve} is simple. There is no need to install a separate management
tool, everything can be done via your web browser (Latest Firefox and
Google Chrome is preferred). To access VM/CT console, a built in HTML5
console is used. As alternative, SPICE can be used.

As we use Proxmox Cluster file system (pmxcfs),you can connect to any
node to manage the whole cluster.

To use the Central Web-based Management, you need a modern browser,
this includes:

* Firefox, a release from the current year, or the latest Enterprise
* Support Release Chrome, a release from the current year
* Microsoft currently supported versions of Edge Browser
* Apple currently supported versions of Safari

If {pve} detect you're connecting from a mobile device, you will
redirected to a light weight touch based UI.

The web interface can be reached via https://youripaddress:8006
(default login is: root, the password is specified during the
installation).


Features
--------

* Seamless integration and management of Proxmox VE 4.x Cluster
* AJAX technologies for dynamic updates of resources
* Secure access to all Virtual Machines and Containers via SSL encryption (https)
* Fast search-driven interface, capable of handling hundreds and probably thousands of VMs
* Secure HTML5 console or SPICE
* Role based permission management for all objects (VMs, storages, nodes, etc.)
* Support for multiple authentication sources (e.g. local, MS ADS, LDAP, ...)
* Two-Factor Authentication
* Proxmox VE Firewall
* Based on Ext JS 6.x JavaScript framework


GUI Overview
------------

[thumbnail="gui-datacenter-summary.png"]

Lets start with the header.
We start on the left side, where the first thing you see is the Proxmox Logo.
Next to it is the current running version of Proxmox VE.
In the search bar it is possible to search for item which the datacenter contains.
After the search-bar the identity is shown (login name).

[thumbnail="gui-my-settings.png"]

The 'my settings' button (Gear Symble) contains dashbord customization,
reset the saved login name or rest the saved layout.
At least four buttons come, started with 'Help', 'Create VM', 'Create CT' and 'Logout'.

The Body has 3 sections:

* On the left side is the navigation bar. On the top, you can select one of 4
  views. Those views change the structure of the tree below. The default
  selection is *Server View* and it has the following 4 types of elements.
** Datacenter: contains all the settings belonging to all machines.
** Nodes: represent the host where the VM/CT runs on. It is named like
   the hostname. Normally the name was set by the installation.
** Entity: can be a VM, container, a template or a storage.
** Logical pools: it is possible to group entities to a group for easy management.
* On the right side is the main management center, where all content
  of the selected entity form the navigation bar is shown.
* On the bottom is the task log section, where all tasks are shown.

Dataceter Level
---------------

[thumbnail="gui-datacenter-search.png"]

On the datacenter level you can access cluster wide settings and information.

* *Search:* it is possible to search anything in cluster
,this can be a node, VM, Container, Storage or a pool.

* *Summary:* gives a brief overview over the cluster health.

* *Options:* can show and set defaults, which apply cluster wide.

* *Storage:* is the place where a storage will add/managed/removed.

* *Backup:* has the capability to schedule Backups. This is
   cluster wide, so you do not care about where the VM/Container are on
   your cluster at schedule time.

* *Permissions:* will manage user and group permission, LDAP,
   MS-AD and Two-Factor authentication can be setup here.

* *HA:* will manage the {pve} High-Availability

* *Firewall:* on this level the Proxmox Firewall works cluster wide and
   makes templates which are cluster wide available.

* *Support:* here you get all information about your support subscription.

If you like to have more information about this see the corresponding chapter.


Node Level
----------

[thumbnail="gui-node-summary.png"]

All belongs of a node can be managed at this level.

* *Search:* it is possible to search anything on the node,
 this can be a VM, Container, Storage or a pool.

* *Summary:* gives a brief overview over the resource usage.

* *Shell:* log you in the shell of the node.

* *System:* is for configuring the network, dns and time, and also shows your syslog.

* *Updates:* will upgrade the system and informs you about new packets.

* *Firewall:* on this level is only for this node.

* *Disk:* gives you an brief overview about you physical hard drives and
   how they are used.

* *Ceph:* is only used if you have installed a Ceph sever on you
   host. Then you can manage your Ceph cluster and see the status
   of it here.

* *Task History:* here all past task are shown.

* *Subscription:* here you can upload you subscription key and get a
   system overview in case of a support case.

VM Level
--------

[thumbnail="gui-qemu-summary.png"]

There are two differed kinds of VM types and both types can be converted to a template.
One of them are Kernel-based Virtual Machine (KVM) and the other one are Linux Containers (LXC).
General the navigation are the same only some option are different.

In the main management center the VM navigation begin if a VM is selected in the left tree.

The top header contains important VM operation commands like 'Start', 'Shutdown', 'Rest',
'Remove', 'Migrate', 'Console' and 'Help'.
Two of them have hidden buttons like 'Shutdown' has 'Stop' and
'Console' contains the different consolen typs 'SPICE' or 'noVNC'.

On the right side the content switch white the focus of the option.

On the left side.
All available options are listed one below the other.

* *Summary:* gives a brief overview over the VM activity.

* *Console:* an interactive console to your VM.

* *(KVM)Hardware:* shows and set the Hardware of the KVM VM.

* *(LXC)Resources:* defines the LXC Hardware opportunities.

* *(LXC)Network:* the LXC Network settings.

* *(LXC)DNS:* the LXC DNS settings.

* *Options:* all VM options can be set here, this distinguishes between KVM and LXC.

* *Task History:* here all previous task from this VM will be shown.

* *(KVM) Monitor:* is the interactive communication interface to the KVM process.

* *Backup:* shows the available backups from this VM and also create a backupset.

* *Snapshots:* manage VM snapshots.

* *Firewall:* manage the firewall on VM level.

* *Permissions:* manage the user permission for this VM.

Storage Level
-------------

// insert storage summary pic

In this view we have a two partition split view.
On the left side we have the storage options
and on the right side the content of the selected option will shown.

* *Summary:* show you important information about your storage like
'Usage', 'Type', 'Content', 'Active' and 'Enabled'.

* *Content:* Here all contend will listed grouped by content.

* *Permissions:* manage the user permission for this storage.

Logical Pool Level
------------------

// insert pool member pic

In this view we have a two partition split view.
On the left side we have the logical pool options
and on the right side the content of the selected option will shown.

* *Summary:* show the description of the pool.

* *Members:* Here all members of this pool will listed and can be managed.

* *Permissions:* manage the user permission for this pool.

ifdef::wiki[]

See Also
--------

* link:/wiki/Central_Web-based_Management

endif::wiki[]

////
TODO:

VM, CT, Storage, Pool section

////
