Package Repositories
--------------------
include::attributes.txt[]

All Debian based systems use
http://en.wikipedia.org/wiki/Advanced_Packaging_Tool[APT] as package
management tool. The list of repositories is defined in
'/etc/apt/sources.list' and '.list' files found inside
'/etc/apt/sources.d/'. Updates can be installed directly using
'apt-get', or via the GUI.

Apt 'sources.list' files list one package repository per line, with
the most preferred source listed first. Empty lines are ignored, and a
'#' character anywhere on a line marks the remainder of that line as a
comment. The information available from the configured sources is
acquired by 'apt-get update'.

.File '/etc/apt/sources.list'
----
deb http://ftp.debian.org/debian jessie main contrib

# security updates
deb http://security.debian.org jessie/updates main contrib
----

In addition, {pve} provides three different package repositories.

{pve} Enterprise Repository
~~~~~~~~~~~~~~~~~~~~~~~~~~~

This is the default, stable and recommended repository, available for
all {pve} subscription users. It contains the most stable packages,
and is suitable for production use. The `pve-enterprise` repository is
enabled by default:

.File '/etc/apt/sources.list.d/pve-enterprise.list'
----
deb https://enterprise.proxmox.com/debian jessie pve-enterprise
----

As soon as updates are available, the `root@pam` user is notified via
email about the available new packages. On the GUI, the change-log of
each package can be viewed (if available), showing all details of the
update. So you will never miss important security fixes.

Please note that and you need a valid subscription key to access this
repository. We offer different support levels, and you can find further
details at http://www.proxmox.com/en/proxmox-ve/pricing.

NOTE: You can disable this repository by commenting out the above line
using a '#' (at the start of the line). This prevents error messages
if you do not have a subscription key. Please configure the
`pve-no-subscription` repository in that case.


{pve} No-Subscription Repository
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

As the name suggests, you do not need a subscription key to access
this repository. It can be used for testing and non-production
use. Its not recommended to run on production servers, as these
packages are not always heavily tested and validated.

We recommend to configure this repository in '/etc/apt/sources.list'.

.File '/etc/apt/sources.list'
----
deb http://ftp.debian.org/debian jessie main contrib

# PVE pve-no-subscription repository provided by proxmox.com,
# NOT recommended for production use
deb http://download.proxmox.com/debian jessie pve-no-subscription

# security updates
deb http://security.debian.org jessie/updates main contrib
----

 
{pve} Test Repository
~~~~~~~~~~~~~~~~~~~~~~

Finally, there is a repository called `pvetest`. This one contains the
latest packages and is heavily used by developers to test new
features. As usual, you can configure this using
'/etc/apt/sources.list' by adding the following line:

.sources.list entry for `pvetest`
----
deb http://download.proxmox.com/debian jessie pvetest
----

WARNING: the `pvetest` repository should (as the name implies) only be used
for testing new features or bug fixes.


ifdef::wiki[]

// include note about older releases, but only for wiki

{pve} 3.x
~~~~~~~~~

{pve} 3.x is based on Debian 7.x ('wheezy'). Please note that this
release is out of date, and you should update your
installation. Nevertheless, we still provide access to those
repositories at our download servers.

[width="100%",cols="<d,3m",options="header"]
|===========================================================
|Repository                 | sources.list entry
|{pve} 3.x Enterprise       |
deb https://enterprise.proxmox.com/debian wheezy pve-enterprise
|{pve} 3.x No-Subscription  |
deb http://download.proxmox.com/debian wheezy pve-no-subscription
|{pve} 3.x Test             |
deb http://download.proxmox.com/debian wheezy pvetest
|===========================================================

NOTE: Apt 'sources.list' configuration files are basically the same as
in newer 4.x versions - just replace 'jessie' with 'wheezy'.

endif::wiki[]
