Installing Proxmox VE
=====================
include::attributes.txt[]

{pve} ships as a set of Debian packages, so you can simply install it
on top of a normal Debian installation, or download the installation
CD-ROM and use that to install {pve} on your hardware.

Installing on top of an existing Debian installation looks easy, but
it presumes that you have correctly installed the base system, and you
know how you want to configure and use the local storage. Network
configuration is also completely up to you.

In general, this is not trivial, especially when you use LVM or
ZFS. This is why we provide an installation CD-ROM for {pve}. That
installer just ask you a few questions, then partitions the local
disk(s), installs all required packages and configures the system
including a basic network setup. You can get a fully functional system
within a few minutes, including the following:

* Complete operating system (Debian Linux, 64-bit)
* Partition the hard drive with ext4 (alternative ext3 or xfs) or ZFS
* {pve} Kernel with LXC and KVM support
* Complete toolset
* Web based management interface

ifndef::wiki[]

include::pve-system-requirements.adoc[]

endif::wiki[]


Using the {pve} Installation CD-ROM
-----------------------------------

This is the preferred and recommended installation method.

NOTE: By default, the complete server is used and all existing data is
removed.

Please insert the installation CD-ROM, then boot from that
drive. Immediately afterwards you can choose the following menu
options:

Install Proxmox VE::

Start normal installation.

Install Proxmox VE (Debug mode)::

Start installation in debug mode. It opens a shell console at several
installation steps, so that you can debug things if something goes
wrong. Please press `CTRL-D` to exit those debug consoles and continue
installation. This option is mostly for developers and not meant for
general use.

Rescue Boot::

This option allows you to boot an existing installation. It searches
all attached hard disks and, if it finds an existing installation,
boots directly into that disk using the existing Linux kernel. This
can be useful if there are problems with the boot block (grub), or the
BIOS is unable to read the boot block from the disk.

Test Memory::

Runs `memtest86+`. This is useful to check if your memory is
functional and error free.

You normally select *Install Proxmox VE* to start the installation.
After that you get prompted to select the target hard disk(s). The
`Options` button lets you select the target file system, which
defaults to `ext4`. The installer uses LVM if you select `ext3`,
`ext4` or `xfs` as file system, and offers additional option to
restrict LVM space (see <<advanced_lvm_options,below>>)

If you have more than one disk, you can also use ZFS as file system.
ZFS supports several software RAID levels, so this is specially useful
if you do not have a hardware RAID controller. The `Options` button
lets you select the ZFS RAID level, and you can choose disks there.

The next pages just ask for basic configuration options like time
zone and keyboard layout. You also need to specify your email address
and superuser (root) password (must have at least 5 characters).

The last step is the network configuration. Please note that you can
use either IPv4 or IPv6 here, but not both. If you want to configure a
dual stack node, you can easily do that after installation.

If you press `Next` now, installation starts to format disks, and
copies packages to the target. Please wait until that is finished,
then reboot the server.

Further configuration is done via the Proxmox web interface. Just
point your browser to the IP address given during installation
(https://youripaddress:8006).

NOTE: Default login is "root" (realm 'PAM') and the root password is
defined during the installation process.


[[advanced_lvm_options]]
Advanced LVM Configuration Options
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

The installer creates a Volume Group (VG) called `pve`, and additional
Logical Volumes (LVs) called `root`, `data` and `swap`. The size of
those volumes can be controlled with:

`hdsize`::

Defines the total HD size to be used. This way you can save free
space on the HD for further partitioning (i.e. for an additional PV
and VG on the same hard disk that can be used for LVM storage).

`swapsize`::

To define the size of the `swap` volume. Default is the same size as
installed RAM, with 4GB minimum and `hdsize/8` as maximum.

`maxroot`::

The `root` volume size. The `root` volume stores the whole operation
system.

`maxvz`::

Define the size of the `data` volume.

`minfree`::

To define the amount of free space left in LVM volume group `pve`.
16GB is the default if storage available > 128GB, `hdsize/8` otherwise.
+
NOTE: LVM requires free space in the VG for snapshot creation (not
required for lvmthin snapshots).


ZFS Performance Tips
~~~~~~~~~~~~~~~~~~~~

ZFS uses a lot of memory, so it is best to add additional RAM if you
want to use ZFS. A good calculation is 4GB plus 1GB RAM for each TB
RAW disk space.

ZFS also provides the feature to use a fast SSD drive as write cache. The
write cache is called the ZFS Intent Log (ZIL). You can add that after
installation using the following command:

 zpool add <pool-name> log </dev/path_to_fast_ssd>


ifdef::wiki[]

link:/wiki/Install_Proxmox_VE_on_Debian_Jessie[Install Proxmox VE on Debian Jessie]
-----------------------------------------------------------------------------------

link:/wiki/Install_from_USB_Stick[Install from USB Stick]
---------------------------------------------------------

endif::wiki[]

ifndef::wiki[]

Install {pve} on Debian
-----------------------

{pve} ships as a set of Debian packages, so you can simply install it
on top of a normal Debian installation. After configuring the
repositories, you need to run:

[source,bash]
----
apt-get update
apt-get install proxmox-ve
----

You can find a detailed step by step howto on the
{webwiki-url}Install_Proxmox_VE_on_Debian_Jessie[wiki].

include::pve-usbstick.adoc[]

endif::wiki[]

ifdef::wiki[]

Video Tutorials
---------------

* List of all official tutorials on our
  http://www.youtube.com/proxmoxve[Proxmox VE YouTube Channel]

* Tutorials in Spanish language on
  http://www.youtube.com/playlist?list=PLUULBIhA5QDBdNf1pcTZ5UXhek63Fij8z[ITexperts.es
  YouTube Play List]


See Also
--------

* link:/wiki/System_Requirements[System Requirements]

* link:/wiki/Package_Repositories[Package Repositories]

* link:/wiki/Host_System_Administration[Host System Administration]

* link:/wiki/Network_Configuration[Network Configuration]

* link:/wiki/Installation:_Tips_and_Tricks[Installation: Tips and Tricks]

endif::wiki[]
