System Requirements
-------------------
ifdef::wiki[]
:pve-toplevel:
endif::wiki[]

For production servers, high quality server equipment is needed. Keep
in mind, if you run 10 Virtual Servers on one machine and you then
experience a hardware failure, 10 services are lost. {pve}
supports clustering, this means that multiple {pve} installations
can be centrally managed thanks to the included cluster functionality.

{pve} can use local storage (DAS), SAN, NAS and also distributed
storage (Ceph RBD). For details see xref:chapter_storage[chapter storage].


Minimum Requirements, for Evaluation
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

* CPU: 64bit (Intel EMT64 or AMD64)

* Intel VT/AMD-V capable CPU/Mainboard for KVM Full Virtualization support

* RAM: 1 GB RAM, plus additional RAM used for guests

* Hard drive

* One NIC


Recommended System Requirements
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

* Intel EMT64 or AMD64 with Intel VT/AMD-V CPU flag.

* Memory, minimum 2 GB for OS and Proxmox VE services. Plus designated memory
  for guests. For Ceph or ZFS additional memory is required, approximately 1 GB
  memory for every TB used storage.

* Fast and redundant storage, best results with SSD disks.

* OS storage: Hardware RAID with batteries protected write cache (``BBU'') or
  non-RAID with ZFS and SSD cache.

* VM storage: For local storage use a hardware RAID with battery backed
  write cache (BBU) or non-RAID for ZFS. Neither ZFS nor Ceph are compatible
  with a hardware RAID controller. Shared and distributed storage is also
  possible.

* Redundant Gbit NICs, additional NICs depending on the preferred storage
  technology and cluster setup – 10 Gbit and higher is also supported.

* For PCI passthrough a CPU with VT-d/AMD-d CPU flag is needed.


Simple Performance Overview
~~~~~~~~~~~~~~~~~~~~~~~~~~~

On an installed {pve} system, you can run the included `pveperf` script
to obtain an overview of the CPU and hard disk performance.

NOTE: this is just a very quick and general benchmark. More detailed tests
are recommended, especially regarding the I/O performance of your system.

Supported web browsers for accessing the web interface
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
To use the web interface you need a modern browser, this includes:

* Firefox, a release from the current year, or the latest Extended
Support Release
* Chrome, a release from the current year
* the Microsoft currently supported versions of Internet Explorer (as
of 2016, this means IE 11 or IE Edge)
* the Apple currently supported versions of Safari (as of 2016, this
means Safari 9)

If {pve} detects you're connecting from a mobile device, you will be
redirected to a lightweight touch-based UI.
