[[sysadmin_package_repositories]]
Package Repositories
--------------------
ifdef::wiki[]
:pve-toplevel:
endif::wiki[]

{pve} uses http://en.wikipedia.org/wiki/Advanced_Packaging_Tool[APT] as its
package management tool like any other Debian-based system. Repositories are
defined in the file `/etc/apt/sources.list` and in `.list` files placed in
`/etc/apt/sources.list.d/`.

Each line defines a package repository. The preferred source must come first.
Empty lines are ignored. A `#` character anywhere on a line marks the remainder
of that line as a comment. The available packages from a repository are acquired
by running `apt-get update`. Updates can be installed directly using `apt-get`,
or via the GUI.

.File `/etc/apt/sources.list`
----
deb http://ftp.debian.org/debian bullseye main contrib
deb http://ftp.debian.org/debian bullseye-updates main contrib

# security updates
deb http://security.debian.org/debian-security bullseye-security main contrib
----

{pve} additionally provides three different package repositories.

[[sysadmin_enterprise_repo]]
{pve} Enterprise Repository
~~~~~~~~~~~~~~~~~~~~~~~~~~~

This is the default, stable, and recommended repository, available for all {pve}
subscription users. It contains the most stable packages and is suitable for
production use. The `pve-enterprise` repository is enabled by default:

.File `/etc/apt/sources.list.d/pve-enterprise.list`
----
deb https://enterprise.proxmox.com/debian/pve bullseye pve-enterprise
----

The `root@pam` user is notified via email about available updates. Click the
'Changelog' button in the GUI to see more details about the selected update.

You need a valid subscription key to access the `pve-enterprise` repository.
Different support levels are available. Further details can be found at
https://www.proxmox.com/en/proxmox-ve/pricing.

NOTE: You can disable this repository by commenting out the above line using a
`#` (at the start of the line). This prevents error messages if you do not have
a subscription key. Please configure the `pve-no-subscription` repository in
that case.

[[sysadmin_no_subscription_repo]]
{pve} No-Subscription Repository
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

This is the recommended repository for testing and non-production use. Its
packages are not as heavily tested and validated. You don't need a subscription key
to access the `pve-no-subscription` repository.

We recommend to configure this repository in `/etc/apt/sources.list`.

.File `/etc/apt/sources.list`
----
deb http://ftp.debian.org/debian bullseye main contrib
deb http://ftp.debian.org/debian bullseye-updates main contrib

# PVE pve-no-subscription repository provided by proxmox.com,
# NOT recommended for production use
deb http://download.proxmox.com/debian/pve bullseye pve-no-subscription

# security updates
deb http://security.debian.org/debian-security bullseye-security main contrib
----


[[sysadmin_test_repo]]
{pve} Test Repository
~~~~~~~~~~~~~~~~~~~~~~

This repository contains the latest packages and is primarily used by developers
to test new features. To configure it, add the following line to
`etc/apt/sources.list`:

.sources.list entry for `pvetest`
----
deb http://download.proxmox.com/debian/pve bullseye pvetest
----

WARNING: The `pvetest` repository should (as the name implies) only be used for
testing new features or bug fixes.

[[sysadmin_package_repositories_ceph]]
Ceph Pacific Repository
~~~~~~~~~~~~~~~~~~~~~~~

NOTE: Ceph Pacific (16.2) was declared stable with {pve} 7.0.

This repository holds the main {pve} Ceph Pacific packages. They are suitable
for production. Use this repository if you run the Ceph client or a full Ceph
cluster on {pve}.

.File `/etc/apt/sources.list.d/ceph.list`
----
deb http://download.proxmox.com/debian/ceph-pacific bullseye main
----


Ceph Pacific Test Repository
~~~~~~~~~~~~~~~~~~~~~~~~~~~~

This Ceph repository contains the Ceph Pacific packages before they are moved
to the main repository. It is used to test new Ceph releases on {pve}.

.File `/etc/apt/sources.list.d/ceph.list`
----
deb http://download.proxmox.com/debian/ceph-pacific bullseye test
----

[[sysadmin_package_repositories_ceph_octopus]]
Ceph Octopus Repository
~~~~~~~~~~~~~~~~~~~~~~~

NOTE: Ceph Octopus (15.2) was declared stable with {pve} 6.3 it will continue
to get updates for the xref:faq-support-table[remaining life time of the 6.x release]
and also for {pve} 7.x until Ceph Octopus upstream EOL (~ 2022-07).

This repository holds the main {pve} Ceph Octopus packages. They are suitable
for production. Use this repository if you run the Ceph client or a full Ceph
cluster on {pve}.

.File `/etc/apt/sources.list.d/ceph.list`
----
deb http://download.proxmox.com/debian/ceph-octopus bullseye main
----

Note that on an older {pve} 6.x you need to change `bullseye` to `buster` in
the repository specification above.


Ceph Octopus Test Repository
~~~~~~~~~~~~~~~~~~~~~~~~~~~~

This Ceph repository contains the Ceph packages before they are moved to the
main repository. It is used to test new Ceph releases on {pve}.

.File `/etc/apt/sources.list.d/ceph.list`
----
deb http://download.proxmox.com/debian/ceph-octopus bullseye test
----

SecureApt
~~~~~~~~~

The 'Release' files in the repositories are signed with GnuPG. APT is using
these signatures to verify that all packages are from a trusted source.

If you install {pve} from an official ISO image, the key for verification is
already installed.

If you install {pve} on top of Debian, download and install
the key with the following commands:

----
 # wget https://enterprise.proxmox.com/debian/proxmox-release-bullseye.gpg -O /etc/apt/trusted.gpg.d/proxmox-release-bullseye.gpg
----

Verify the checksum afterwards with:

----
# sha512sum /etc/apt/trusted.gpg.d/proxmox-release-bullseye.gpg
----

The output should be:

----
7fb03ec8a1675723d2853b84aa4fdb49a46a3bb72b9951361488bfd19b29aab0a789a4f8c7406e71a69aabbc727c936d3549731c4659ffa1a08f44db8fdcebfa /etc/apt/trusted.gpg.d/proxmox-release-bullseye.gpg
----

or:

----
# md5sum /etc/apt/trusted.gpg.d/proxmox-release-bullseye.gpg
----
The output should be:

----
bcc35c7173e0845c0d6ad6470b70f50e /etc/apt/trusted.gpg.d/proxmox-release-bullseye.gpg
----


ifdef::wiki[]

// include note about older releases, but only for wiki


{pve} 6.x Repositories
~~~~~~~~~~~~~~~~~~~~~~

{pve} 6.x is based on Debian 10.x (``buster''). Please note that this release is
out of date. Existing installations should be updated. Nevertheless access to
these repositories is still provided.

[width="100%",cols="<d,3m",options="header"]
|===========================================================
|Repository                 | sources.list entry
|{pve} 6.x Enterprise       |
deb https://enterprise.proxmox.com/debian buster pve-enterprise
|{pve} 6.x No-Subscription  |
deb http://download.proxmox.com/debian buster pve-no-subscription
|{pve} 6.x Test             |
deb http://download.proxmox.com/debian buster pvetest
|===========================================================


{pve} 5.x Repositories
~~~~~~~~~~~~~~~~~~~~~~

{pve} 5.x is based on Debian 9.x (``stretch''). Please note that this release is
out of date. Existing installations should be updated. Nevertheless access to
these repositories is still provided.

[width="100%",cols="<d,3m",options="header"]
|===========================================================
|Repository                 | sources.list entry
|{pve} 5.x Enterprise       |
deb https://enterprise.proxmox.com/debian stretch pve-enterprise
|{pve} 5.x No-Subscription  |
deb http://download.proxmox.com/debian stretch pve-no-subscription
|{pve} 5.x Test             |
deb http://download.proxmox.com/debian stretch pvetest
|===========================================================


{pve} 4.x Repositories
~~~~~~~~~~~~~~~~~~~~~~

{pve} 4.x is based on Debian 8.x (``jessie''). Please note that this release is
out of date. Existing installations should be updated. Nevertheless access to
these repositories is still provided.

[width="100%",cols="<d,3m",options="header"]
|===========================================================
|Repository                 | sources.list entry
|{pve} 4.x Enterprise       |
deb https://enterprise.proxmox.com/debian jessie pve-enterprise
|{pve} 4.x No-Subscription  |
deb http://download.proxmox.com/debian jessie pve-no-subscription
|{pve} 4.x Test             |
deb http://download.proxmox.com/debian jessie pvetest
|===========================================================


{pve} 3.x Repositories
~~~~~~~~~~~~~~~~~~~~~~

{pve} 3.x is based on Debian 7.x (``wheezy''). Please note that this release is
out of date. Existing installations should be updated. Nevertheless access to
these repositories is still provided.

[width="100%",cols="<d,3m",options="header"]
|===========================================================
|Repository                 | sources.list entry
|{pve} 3.x Enterprise       |
deb https://enterprise.proxmox.com/debian wheezy pve-enterprise
|{pve} 3.x No-Subscription  |
deb http://download.proxmox.com/debian wheezy pve-no-subscription
|{pve} 3.x Test             |
deb http://download.proxmox.com/debian wheezy pvetest
|===========================================================


Outdated: `stable` Repository `pve`
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

This repository is a leftover to ease the update to 3.1. It will not get any
updates after the release of 3.1. Therefore the repository needs to be removed
after the upgrade to 3.1.

.File `/etc/apt/sources.list`
----
deb http://ftp.debian.org/debian wheezy main contrib

# PVE packages provided by proxmox.com - NO UPDATES after the initial release of 3.1
# deb http://download.proxmox.com/debian wheezy pve

# security updates
deb http://security.debian.org/ wheezy/updates main contrib
----


Outdated: {pve} 2.x Repositories
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

{pve} 2.x is based on Debian 6.0 (``squeeze'') and outdated. Please upgrade to
the latest version as soon as possible. In order to use the stable `pve` 2.x
repository, check your sources.list:

.File `/etc/apt/sources.list`
----
deb http://ftp.debian.org/debian squeeze main contrib

# PVE packages provided by proxmox.com
deb http://download.proxmox.com/debian squeeze pve

# security updates
deb http://security.debian.org/ squeeze/updates main contrib
----


Outdated: {pve} VE 1.x Repositories
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

{pve} 1.x is based on Debian 5.0 (``lenny'') and very outdated. Please upgrade
to latest version as soon as possible.


endif::wiki[]
ifdef::manvolnum[]
include::pve-copyright.adoc[]
endif::manvolnum[]
