[[installation_prepare_media]]
Prepare Installation Media
--------------------------
ifdef::wiki[]
:pve-toplevel:
endif::wiki[]

Download the installer ISO image from: {website}en/downloads/category/iso-images-pve

The {pve} installation media is a hybrid ISO image. It works in two ways:

* An ISO image file ready to burn to a CD or DVD.

* A raw sector (IMG) image file ready to copy to a USB flash drive (USB stick).

Using a USB flash drive to install {pve} is the recommended way because it is
the faster option.

Prepare a USB Flash Drive as Installation Medium
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

The flash drive needs to have at least 1 GB of storage available.

NOTE: Do not use UNetbootin. It does not work with the {pve} installation image.

IMPORTANT: Make sure that the USB flash drive is not mounted and does not
contain any important data.


Instructions for GNU/Linux
~~~~~~~~~~~~~~~~~~~~~~~~~~

On Unix-like operating system use the `dd` command to copy the ISO image to the
USB flash drive. First find the correct device name of the USB flash drive (see
below). Then run the `dd` command.

----
# dd if=proxmox-ve_*.iso of=/dev/XYZ bs=1M
----

NOTE: Be sure to replace /dev/XYZ with the correct device name.

CAUTION: Be very careful, and do not overwrite the wrong disk!


Find the Correct USB Device Name
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
There are two ways to find out the name of the USB flash drive. The first one is
to compare the last lines of the `dmesg` command output before and after
plugging in the flash drive. The second way is to compare the output of the
`lsblk` command. Open a terminal and run:

----
# lsblk
----

Then plug in your USB flash drive and run the command again:

----
# lsblk
----

A new device will appear. This is the one you want to use. To be on the extra
safe side check if the reported size matches your USB flash drive.


Instructions for macOS
~~~~~~~~~~~~~~~~~~~~~~

Open the terminal (query Terminal in Spotlight).

Convert the .iso file to .img using the convert option of `hdiutil` for example.

----
# hdiutil convert -format UDRW -o proxmox-ve_*.dmg proxmox-ve_*.iso
----

TIP: macOS tends to automatically add '.dmg' to the output file name.

To get the current list of devices run the command:

----
# diskutil list
----

Now insert the USB flash drive and run this command again to determine which
device node has been assigned to it. (e.g., /dev/diskX).

----
# diskutil list
# diskutil unmountDisk /dev/diskX
----

NOTE: replace X with the disk number from the last command.

----
# sudo dd if=proxmox-ve_*.dmg of=/dev/rdiskX bs=1m
----

NOTE: 'rdiskX', instead of 'diskX', in the last command is intended. It will
increase the write speed.

Instructions for Windows
~~~~~~~~~~~~~~~~~~~~~~~~

Download Rufus from https://rufus.ie/. Either install it or use the portable
version. Select the destination drive and the {pve} ISO file.

Once you click 'Start' a dialog asking to download a different version of GRUB
will show up. Click 'No'. In the next dialog select the 'DD' mode.

An alternative to Rufus is Etcher. Download Etcher from https://etcher.io. It
will guide you through the process of selecting the ISO and your USB Drive.

ifdef::wiki[]
Boot your Server from the USB Flash Drive
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Connect the USB flash drive to your server and make sure that booting from USB
is enabled (check your servers firmware settings). Then follow the steps in the
xref:chapter_installation[installation wizard].

endif::wiki[]
