[[storage_lvm]]
LVM Backend
-----------
ifdef::wiki[]
:pve-toplevel:
:title: Storage: LVM
endif::wiki[]

Storage pool type: `lvm`

LVM is a light software layer on top of hard disks and partitions. It
can be used to split available disk space into smaller logical
volumes. LVM is widely used on Linux and makes managing hard drives
easier.

Another use case is to put LVM on top of a big iSCSI LUN. That way you
can easily manage space on that iSCSI LUN, which would not be possible
otherwise, because the iSCSI specification does not define a
management interface for space allocation.


[[pvesm_lvm_config]]
Configuration
~~~~~~~~~~~~~

The LVM backend supports the common storage properties `content`, `nodes`,
`disable`, and the following LVM specific properties:

`vgname`::

LVM volume group name. This must point to an existing volume group.

`base`::

Base volume. This volume is automatically activated before accessing
the storage. This is mostly useful when the LVM volume group resides
on a remote iSCSI server.

`saferemove`::

Called "Wipe Removed Volumes" in the web UI. Zero-out data when removing LVs.
When removing a volume, this makes sure that all data gets erased and cannot be
accessed by other LVs created later (which happen to be assigned the same
physical extents). This is a costly operation, but may be required as a security
measure in certain environments.

`saferemove_throughput`::

Wipe throughput (`cstream -t` parameter value).

`snapshot-as-volume-chain`::

Set this flag to enable snapshot support for virtual machines on LVM with a
volume backing chain.
With this setting, taking a snapshot persists the current state under the
snapshot's name and starts a new volume backed by the snapshot.
+
A volume based on a snapshot references its parent snapshot volume as its
backing volume and records only the differences to that backing volume.
Snapshot volumes are currently thick-provisioned LVM logical volumes, but the
underlying block storage may provide thin provisioning.
+
This design avoids issues with native LVM snapshots, such as significant
input/output (I/O) penalties and unexpected, dangerous behavior when running out
of pre-allocated space.
+
Snapshots as volume chains provide vendor-agnostic support for snapshots on any
storage system that supports block storage. This includes iSCSI and Fiber
Channel-attached SANs.
+
Note that, although this feature relies on qcow2, it only uses qcow2's ability
to layer multiple volumes in a backing chain, not qcow2's snapshot
functionality.
The snapshot functionality is managed by the PVE storage system.
+
Enabling or disabling this flag only affects newly created virtual disk volumes.

.Configuration Example (`/etc/pve/storage.cfg`)
----
lvm: myspace
	vgname myspace
	content rootdir,images
----

File naming conventions
~~~~~~~~~~~~~~~~~~~~~~~

The backend use basically the same naming conventions as the ZFS pool
backend.

 vm-<VMID>-<NAME>      // normal VM images

Storage Features
~~~~~~~~~~~~~~~~

LVM is a typical block storage, but this backend does not support
snapshots and clones. Unfortunately, normal LVM snapshots are quite
inefficient, because they interfere with all writes on the entire volume
group during snapshot time.

One big advantage is that you can use it on top of a shared storage,
for example, an iSCSI LUN. The backend itself implements proper cluster-wide
locking.

TIP: The newer LVM-thin backend allows snapshots and clones, but does
not support shared storage.


.Storage features for backend `lvm`
[width="100%",cols="m,m,3*d",options="header"]
|==============================================================================
|Content types  |Image formats  |Shared   |Snapshots |Clones
|images rootdir |raw            |possible |no        |no
|==============================================================================

Examples
~~~~~~~~

You can get a list of available LVM volume groups with:

 # pvesm scan lvm

ifdef::wiki[]

See Also
~~~~~~~~

* link:/wiki/Storage[Storage]

endif::wiki[]


