System Requirements
-------------------
ifdef::wiki[]
:pve-toplevel:
endif::wiki[]

For production servers, high quality server equipment is needed. Keep
in mind, if you run 10 Virtual Servers on one machine and you then
experience a hardware failure, 10 services are lost. {pve}
supports clustering, this means that multiple {pve} installations
can be centrally managed thanks to the included cluster functionality.

{pve} can use local storage (DAS), SAN, NAS and also distributed
storage (Ceph RBD). For details see xref:chapter_storage[chapter storage].


Minimum Requirements, for Evaluation
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

* CPU: 64bit (Intel EMT64 or AMD64)

* Intel VT/AMD-V capable CPU/Mainboard for KVM Full Virtualization support

* RAM: 1 GB RAM, plus additional RAM used for guests

* Hard drive

* One NIC


Recommended System Requirements
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

* CPU: 64bit (Intel EMT64 or AMD64), Multi core CPU recommended

* Intel VT/AMD-V capable CPU/Mainboard for KVM Full Virtualization support

* RAM: 8 GB RAM, plus additional RAM used for guests

* Hardware RAID with batteries protected write cache (``BBU'') or flash
 based protection

* Fast hard drives, best results with 15k rpm SAS, Raid10

* At least two NICs, depending on the used storage technology you need more


Simple Performance Overview
~~~~~~~~~~~~~~~~~~~~~~~~~~~

On an installed {pve} system, you can run the included `pveperf` script
to obtain an overview of the CPU and hard disk performance.

NOTE: this is just a very quick and general benchmark. More detailed tests
are recommended, especially regarding the I/O performance of your system.

Supported web browsers for accessing the web interface
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
To use the web interface you need a modern browser, this includes:

* Firefox, a release from the current year, or the latest Extended
Support Release
* Chrome, a release from the current year
* the Microsoft currently supported versions of Internet Explorer (as
of 2016, this means IE 11 or IE Edge)
* the Apple currently supported versions of Safari (as of 2016, this
means Safari 9)

If {pve} detects you're connecting from a mobile device, you will be
redirected to a lightweight touch-based UI.
