Frequently Asked Questions
--------------------------
include::attributes.txt[]

NOTE: New FAQs are appended to the bottom of this section.

/////////////////////////////////////////////////////////////////
ADD NEW FAQS TO THE BOTTOM OF THIS SECTION TO MAINTAIN NUMBERING
/////////////////////////////////////////////////////////////////

[qanda]

What distribution is {pve} based on?::

{pve} is based on http://www.debian.org[Debian GNU/Linux]

What license does the {pve} project use?::

{pve} code is licensed under the GNU Affero General Public License,
version 3.

Will {pve} run on a 32bit processor?::

{pve} works only on 64-bit CPU´s (AMD or Intel). There is no plan
for 32-bit for the platform.
+
NOTE: VMs and Containers can be both 32-bit and/or 64-bit.

Does my CPU support virtualization?::

To check if your CPU is virtualization compatible, check for the "vmx"
or "svm" tag in this command output:
+
----
egrep '(vmx|svm)' /proc/cpuinfo
----

Supported Intel CPUs::

64-bit processors with
http://en.wikipedia.org/wiki/Virtualization_Technology#Intel_virtualization_.28VT-x.29[Intel
Virtualization Technology (Intel VT-x)] support. (http://ark.intel.com/search/advanced/?s=t&VTX=true&InstructionSet=64-bit[List of processors with Intel VT and 64-bit])

Supported AMD CPUs::

64-bit processors with
http://en.wikipedia.org/wiki/Virtualization_Technology#AMD_virtualization_.28AMD-V.29[AMD
Virtualization Technology (AMD-V)] support.

What is a container, CT, VE, Virtual Private Server, VPS?::

Operating-system-level virtualization is a server-virtualization
method where the kernel of an operating system allows for multiple
isolated user-space instances, instead of just one. We call such
instances containers. As containers share the Kernel they are
limited to Linux guests.

What is a QEMU/KVM guest (or VM)?::

A QEMU/KVM guest (or VM) is a guest system running virtualized under
{pve} using QEMU and the Linux KVM kernel module.

What is QEMU?::

QEMU is a generic and open source machine emulator and
virtualizer. QEMU uses the Linux KVM kernel module to achieve near
native performance by executing the guest code directly on the host
CPU.
It is not limited to Linux guests but allows arbitrary operating systems
to run.
