ifdef::manvolnum[]
pvenode(1)
==========
:pve-toplevel:

NAME
----

pvenode - Proxmox VE Node Management

SYNOPSIS
--------

include::pvenode.1-synopsis.adoc[]

DESCRIPTION
-----------
endif::manvolnum[]
ifndef::manvolnum[]
Proxmox Node Management
-----------------------
ifdef::wiki[]
:pve-toplevel:
endif::wiki[]
endif::manvolnum[]

The {PVE} node management tool (`pvenode`) allows to control node specific
settings and resources.

Currently `pvenode` allows to set a node's description and to manage
the node's SSL certificates used for the API and the web GUI through `pveproxy`.

ifdef::manvolnum[]
include::output-format.adoc[]

Examples
~~~~~~~~

.Install an externally provided certificate

`pvenode cert set certificate.crt certificate.key -force`

Both files need to be PEM encoded. `certificate.key` contains the private key
and `certificate.crt` contains the whole certificate chain.

.Setup ACME account and order a certificate for local node.

-----
pvenode acme account register default mail@example.invalid
pvenode config set --acme domains=example.invalid
pvenode acme cert order
systemctl restart pveproxy
-----

endif::manvolnum[]

Wake-on-LAN
~~~~~~~~~~~
Wake-on-LAN (WoL) allows to switch on a sleeping computer in the network by
sending a magic packet. At least one NIC must support this feature and the
respective option needs to be enabled in the computers firmware (BIOS/UEFI)
configuration. The option name can vary from 'Enable Wake-on-Lan' to
'Power On By PCIE Device', check your motherboards vendor manual, if unsure.
`ethtool` can be used to check the WoL configuration of `<interface>` by
running:

----
ethtool <interface> | grep Wake-on
----

`pvenode` allows to wake sleeping members of a cluster via WoL using the
command:

----
pvenode wakeonlan <node>
----

This broadcasts the WoL magic packet on UDP port 9, containing the MAC address
of `<node>` obtained from the `wakeonlan` property. The node specific
`wakeonlan` property can be set by the following command:

----
pvenode config set -wakeonlan XX:XX:XX:XX:XX:XX
----


[[first_guest_boot_delay]]
First Guest Boot Delay
~~~~~~~~~~~~~~~~~~~~~~

In case your VMs/containers rely on slow-to-start external resources, for
example an NFS server, you can also set a per-node delay between the time {pve}
boots and the time the first VM/container that is configured to autostart boots
(see xref:qm_startup_and_shutdown[Automatic Start and Shutdown of Virtual Machines]).

You can achieve this by setting the following (where `10` represents the delay
in seconds):

----
pvenode config set --startall-onboot-delay 10
----


// TODO: extend and improve chapter!

ifdef::manvolnum[]
include::pve-copyright.adoc[]
endif::manvolnum[]
