Host System Administration
==========================
include::attributes.txt[]

{pve} is based on the famous https://www.debian.org/[Debian] Linux
distribution. That means that you have access to the whole world of
Debian packages, and the base system is well documented. The
https://debian-handbook.info/download/stable/debian-handbook.pdf[Debian
Administrator\'s Handbook] is available online, and provides a
comprehensive introduction to the Debian operating system (see
xref:Hertzog13[]).

A standard {pve} installation uses the default repositories from
Debian, so you get bug fixes and security updates through that
channel. In addition, we provide our own package repository to roll
out all {pve} related packages. This includes updates to some
Debian packages when necessary.

We also deliver a specially optimized Linux kernel, where we enable all
required virtualization and container features. That kernel includes
drivers for http://zfsonlinux.org/[ZFS], and several hardware drivers.
For example, we ship Intel network card drivers to support their
newest hardware.

The following sections will concentrate on virtualization related
topics. They either explains things which are different on {pve}, or
tasks which are commonly used on {pve}. For other topics, please refer
to the standard Debian documentation.

System requirements
-------------------

For production servers, high quality server equipment is needed. Keep
in mind, if you run 10 Virtual Servers on one machine and you then
experience a hardware failure, 10 services are lost. {pve}
supports clustering, this means that multiple {pve} installations
can be centrally managed thanks to the included cluster functionality.

{pve} can use local storage (DAS), SAN, NAS and also distributed
storage (Ceph RBD). For details see xref:chapter-storage[chapter storage].

Minimum requirements, for evaluation
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

* CPU: 64bit (Intel EMT64 or AMD64)

* Intel VT/AMD-V capable CPU/Mainboard for KVM Full Virtualization support

* RAM: 1 GB RAM, plus additional RAM used for guests

* Hard drive

* One NIC

Recommended system requirements
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

* CPU: 64bit (Intel EMT64 or AMD64), Multi core CPU recommended

* Intel VT/AMD-V capable CPU/Mainboard for KVM Full Virtualization support

* RAM: 8 GB RAM, plus additional RAM used for guests

* Hardware RAID with batteries protected write cache (``BBU'') or flash
 based protection

* Fast hard drives, best results with 15k rpm SAS, Raid10

* At least two NICs, depending on the used storage technology you need more

ifdef::wiki[]

See Also
--------

* link:/wiki/Getting_Help[Getting Help]

* link:/wiki/Package_Repositories[Package Repositories]

* link:/wiki/Installation[Installation]

* link:/wiki/Network_Configuration[Network Configuration] 

* link:/wiki/System_Software_Updates[System Software Updates]

* link:/wiki/Logical_Volume_Manager_(LVM)[Logical Volume Manager (LVM)]

* link:/wiki/ZFS_on_Linux[ZFS on Linux]

endif::wiki[]


ifndef::wiki[]

include::pve-package-repos.adoc[]

include::pve-installation.adoc[]

include::system-software-updates.adoc[]

include::pve-network.adoc[]

include::local-lvm.adoc[]

include::local-zfs.adoc[]

endif::wiki[]


////
TODO:

Working with 'systemd'
----------------------

Journal and syslog
~~~~~~~~~~~~~~~~~~

TODO: explain persistent journal...

////
