[[chapter_system_administration]]
Host System Administration
==========================
include::attributes.txt[]
ifndef::manvolnum[]
:pve-toplevel:
endif::manvolnum[]

{pve} is based on the famous https://www.debian.org/[Debian] Linux
distribution. That means that you have access to the whole world of
Debian packages, and the base system is well documented. The
https://debian-handbook.info/download/stable/debian-handbook.pdf[Debian
Administrator\'s Handbook] is available online, and provides a
comprehensive introduction to the Debian operating system (see
xref:Hertzog13[]).

A standard {pve} installation uses the default repositories from
Debian, so you get bug fixes and security updates through that
channel. In addition, we provide our own package repository to roll
out all {pve} related packages. This includes updates to some
Debian packages when necessary.

We also deliver a specially optimized Linux kernel, where we enable all
required virtualization and container features. That kernel includes
drivers for http://zfsonlinux.org/[ZFS], and several hardware drivers.
For example, we ship Intel network card drivers to support their
newest hardware.

The following sections will concentrate on virtualization related
topics. They either explains things which are different on {pve}, or
tasks which are commonly used on {pve}. For other topics, please refer
to the standard Debian documentation.


ifdef::wiki[]

See Also
--------

* link:/wiki/Package_Repositories[Package Repositories]

* link:/wiki/Network_Configuration[Network Configuration] 

* link:/wiki/System_Software_Updates[System Software Updates]

* link:/wiki/External_Metric_Server[External Metric Server]

* link:/wiki/Disk_Health_Monitoring[Disk Health Monitoring]

* link:/wiki/Logical_Volume_Manager_(LVM)[Logical Volume Manager (LVM)]

* link:/wiki/ZFS_on_Linux[ZFS on Linux]

endif::wiki[]


ifndef::wiki[]

include::pve-package-repos.adoc[]

include::system-software-updates.adoc[]

include::pve-network.adoc[]

include::system-timesync.adoc[]

include::pve-external-metric-server.adoc[]

include::pve-disk-health-monitoring.adoc[]

include::local-lvm.adoc[]

include::local-zfs.adoc[]

endif::wiki[]


////
TODO:

Working with 'systemd'
----------------------

Journal and syslog
~~~~~~~~~~~~~~~~~~

TODO: explain persistent journal...

////
