[[translation]]
Translating {pve}
-----------------
ifdef::wiki[]
:pve-toplevel:
endif::wiki[]


The {pve} user interface is in English by default. Thanks to contributions by
the community, translations to other languages are available. We welcome help to
add new languages, translate the newest features, and improve incomplete or
inconsistent translations.

The language files are available as a
https://git.proxmox.com/?p=proxmox-i18n.git[git repository]. If you are familiar
with git, please contribute according to our
{webwiki-url}Developer_Documentation[Developer Documentation].

Even if you are not familiar with git, you can help with translating {pve}.
Download the language files
https://git.proxmox.com/?p=proxmox-i18n.git;a=tree[here]. Then choose the
language you want to improve. Right click on the "raw" link of this language
file, and select 'Save Link As...'. Make your changes to the file, and then
send your final translation directly to office(at)proxmox.com together with a
signed
{webwiki-url}Developer_Documentation#Software_License_and_Copyright[contributor license agreement].

We use https://www.gnu.org/software/gettext/[gettext] for the management of the
translation files. Tools like https://poedit.net/[Poedit] offer a nice user
interface to edit the translation files.
