ifdef::manvolnum[]
PVE({manvolnum})
================
include::attributes.txt[]

NAME
----

vzdump - Backup Utility for VMs and Containers 


SYNOPSYS
--------

include::vzdump.1-synopsis.adoc[]


DESCRIPTION
-----------
endif::manvolnum[]

ifndef::manvolnum[]
Backup and Restore
==================
include::attributes.txt[]
endif::manvolnum[]

Backups are a requirements for any sensible IT deployment, and {pve}
provides a fully integrated solution, using the capabilities of each
storage and each guest system type. This allows the system
administrator to fine tune via the `mode` option between consistency
of the backups and downtime of the guest system.

{pve} backups are always full backups - containing the VM/CT
configuration and all data.  Backups can be started via the GUI or via
the `vzdump` command line tool.

.Backup Storage

Before a backup can run, a backup storage must be defined. Refer to
the Storage documentation on how to add a storage. A backup storage
must be a file level storage, as backups are stored as regular files.
In most situations, using a NFS server is a good way to store backups.
You can save those backups later to a tape drive, for off-site
archiving.

.Scheduled Backup

Backup jobs can be scheduled so that they are executed automatically
on specific days and times, for selectable nodes and guest systems.
Configuration of scheduled backups is done at the Datacenter level in
the GUI, which will generate a cron entry in /etc/cron.d/vzdump.

Backup modes
------------

There are several ways to provide consistency (option `mode`), 
depending on the guest type.

.Backup modes for VMs:

`stop` mode::

This mode provides the highest consistency of the backup, at the cost
of a downtime in the VM operation.  It works by executing an orderly
shutdown of the VM, and then runs a background Qemu process to backup
the VM data. After the backup is complete, the Qemu process resumes
the VM to full operation mode if it was previously running.

`suspend` mode::

This mode is provided for compatibility reason, and suspends the VM
before calling the `snapshot` mode. Since suspending the VM results in
a longer downtime and does not necessarily improve the data
consistency, the use of the `snapshot` mode is recommended instead.

`snapshot` mode::

This mode provides the lowest operation downtime, at the cost of a
small inconstancy risk.  It works by performing a Proxmox VE live
backup, in which data blocks are copied while the VM is running. If the
guest agent is enabled (`agent: 1`) and running, it calls
'guest-fsfreeze-freeze' and 'guest-fsfreeze-thaw' to improve
consistency.

A technical overview of the Proxmox VE live backup for QemuServer can
be found online
https://git.proxmox.com/?p=pve-qemu-kvm.git;a=blob;f=backup.txt[here].

NOTE: Proxmox VE live backup provides snapshot-like semantics on any
storage type. It does not require that the underlying storage supports
snapshots.

.Backup modes for Containers:

`stop` mode::

Stop the container for the duration of the backup. This potentially
results in a very long downtime.

`suspend` mode::

This mode uses rsync to copy the container data to a temporary
location (see option `--tmpdir`). Then the container is suspended and
a second rsync copies changed files. After that, the container is
started (resumed) again. This results in minimal downtime, but needs
additional space to hold the container copy.
+
When the container is on a local filesystem and the target storage of
the backup is an NFS server, you should set `--tmpdir` to reside on a
local filesystem too, as this will result in a many fold performance
improvement.  Use of a local `tmpdir` is also required if you want to
backup a local container using ACLs in suspend mode if the backup
storage is an NFS server.

`snapshot` mode::

This mode uses the snapshotting facilities of the underlying
storage. First, the container will be suspended to ensure data consistency.
A temporary snapshot of the container's volumes will be made and the
snapshot content will be archived in a tar file. Finally, the temporary
snapshot is deleted again.

NOTE: `snapshot` mode requires that all backed up volumes are on a storage that
supports snapshots. Using the `backup=no` mountpoint option individual volumes
can be excluded from the backup (and thus this requirement).

NOTE: bind and device mountpoints are skipped during backup operations, like
volume mountpoints with the backup option disabled.


Backup File Names
-----------------

Newer versions of vzdump encode the guest type and the
backup time into the filename, for example

 vzdump-lxc-105-2009_10_09-11_04_43.tar

That way it is possible to store several backup in the same
directory. The parameter `maxfiles` can be used to specify the
maximum number of backups to keep.

Restore
-------

The resulting archive files can be restored with the following programs.


`pct restore`:: Container restore utility

`qmrestore`:: QemuServer restore utility

For details see the corresponding manual pages.

Configuration
-------------

Global configuration is stored in '/etc/vzdump.conf'. The file uses a
simple colon separated key/value format. Each line has the following
format:

 OPTION: value

Blank lines in the file are ignored, and lines starting with a '#'
character are treated as comments and are also ignored. Values from
this file are used as default, and can be overwritten on the command
line.

We currently support the following options:

include::vzdump.conf.5-opts.adoc[]


.Example 'vzdump.conf' Configuration
----
tmpdir: /mnt/fast_local_disk
storage: my_backup_storage
mode: snapshot
bwlimit: 10000
----

Hook Scripts
------------

You can specify a hook script with option `--script`. This script is
called at various phases of the backup process, with parameters
accordingly set. You can find an example in the documentation
directory ('vzdump-hook-script.pl').

File Exclusions
---------------

NOTE: this option is only available for container backups.

'vzdump' skips the following files by default (disable with the option
`--stdexcludes 0`)

 /tmp/?*
 /var/tmp/?*
 /var/run/?*pid

You can also manually specify (additional) exclude paths, for example:

 # vzdump 777 --exclude-path /tmp/ --exclude-path '/var/foo*'

(only excludes tmp directories)

Configuration files are also stored inside the backup archive
(in `./etc/vzdump/`) and will be correctly restored.

Examples
--------

Simply dump guest 777 - no snapshot, just archive the guest private area and
configuration files to the default dump directory (usually
'/var/lib/vz/dump/').

 # vzdump 777

Use rsync and suspend/resume to create a snapshot (minimal downtime).

 # vzdump 777 --mode suspend

Backup all guest systems and send notification mails to root and admin.

 # vzdump --all --mode suspend --mailto root --mailto admin

Use snapshot mode (no downtime) and non-default dump directory.

 # vzdump 777 --dumpdir /mnt/backup --mode snapshot

Backup more than one guest (selectively)

 # vzdump 101 102 103 --mailto root

Backup all guests excluding 101 and 102

 # vzdump --mode suspend --exclude 101,102

Restore a container to a new CT 600

 # pct restore 600 /mnt/backup/vzdump-lxc-777.tar

Restore a QemuServer VM to VM 601

 # qmrestore /mnt/backup/vzdump-qemu-888.vma 601

Clone an existing container 101 to a new container 300 with a 4GB root
file system, using pipes

 # vzdump 101 --stdout | pct restore --rootfs 4 300 -


ifdef::manvolnum[]
include::pve-copyright.adoc[]
endif::manvolnum[]

